/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const CxdesignIndexLazyImport = createFileRoute('/cxdesign/')()
const CxdesignWebDesignLazyImport = createFileRoute('/cxdesign/web-design')()
const CxdesignLocationLazyImport = createFileRoute('/cxdesign/location')()
const CxdesignGraphicDesignLazyImport = createFileRoute(
  '/cxdesign/graphic-design',
)()
const CxdesignContactLazyImport = createFileRoute('/cxdesign/contact')()
const CxdesignAppDesignLazyImport = createFileRoute('/cxdesign/app-design')()
const CxdesignAboutLazyImport = createFileRoute('/cxdesign/about')()

// Create/Update Routes

const CxdesignIndexLazyRoute = CxdesignIndexLazyImport.update({
  id: '/cxdesign/',
  path: '/cxdesign/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/cxdesign.index.lazy').then((d) => d.Route),
)

const CxdesignWebDesignLazyRoute = CxdesignWebDesignLazyImport.update({
  id: '/cxdesign/web-design',
  path: '/cxdesign/web-design',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/cxdesign.web-design.lazy').then((d) => d.Route),
)

const CxdesignLocationLazyRoute = CxdesignLocationLazyImport.update({
  id: '/cxdesign/location',
  path: '/cxdesign/location',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/cxdesign.location.lazy').then((d) => d.Route),
)

const CxdesignGraphicDesignLazyRoute = CxdesignGraphicDesignLazyImport.update({
  id: '/cxdesign/graphic-design',
  path: '/cxdesign/graphic-design',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/cxdesign.graphic-design.lazy').then((d) => d.Route),
)

const CxdesignContactLazyRoute = CxdesignContactLazyImport.update({
  id: '/cxdesign/contact',
  path: '/cxdesign/contact',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/cxdesign.contact.lazy').then((d) => d.Route),
)

const CxdesignAppDesignLazyRoute = CxdesignAppDesignLazyImport.update({
  id: '/cxdesign/app-design',
  path: '/cxdesign/app-design',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/cxdesign.app-design.lazy').then((d) => d.Route),
)

const CxdesignAboutLazyRoute = CxdesignAboutLazyImport.update({
  id: '/cxdesign/about',
  path: '/cxdesign/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/cxdesign.about.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cxdesign/about': {
      id: '/cxdesign/about'
      path: '/cxdesign/about'
      fullPath: '/cxdesign/about'
      preLoaderRoute: typeof CxdesignAboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/cxdesign/app-design': {
      id: '/cxdesign/app-design'
      path: '/cxdesign/app-design'
      fullPath: '/cxdesign/app-design'
      preLoaderRoute: typeof CxdesignAppDesignLazyImport
      parentRoute: typeof rootRoute
    }
    '/cxdesign/contact': {
      id: '/cxdesign/contact'
      path: '/cxdesign/contact'
      fullPath: '/cxdesign/contact'
      preLoaderRoute: typeof CxdesignContactLazyImport
      parentRoute: typeof rootRoute
    }
    '/cxdesign/graphic-design': {
      id: '/cxdesign/graphic-design'
      path: '/cxdesign/graphic-design'
      fullPath: '/cxdesign/graphic-design'
      preLoaderRoute: typeof CxdesignGraphicDesignLazyImport
      parentRoute: typeof rootRoute
    }
    '/cxdesign/location': {
      id: '/cxdesign/location'
      path: '/cxdesign/location'
      fullPath: '/cxdesign/location'
      preLoaderRoute: typeof CxdesignLocationLazyImport
      parentRoute: typeof rootRoute
    }
    '/cxdesign/web-design': {
      id: '/cxdesign/web-design'
      path: '/cxdesign/web-design'
      fullPath: '/cxdesign/web-design'
      preLoaderRoute: typeof CxdesignWebDesignLazyImport
      parentRoute: typeof rootRoute
    }
    '/cxdesign/': {
      id: '/cxdesign/'
      path: '/cxdesign'
      fullPath: '/cxdesign'
      preLoaderRoute: typeof CxdesignIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/cxdesign/about': typeof CxdesignAboutLazyRoute
  '/cxdesign/app-design': typeof CxdesignAppDesignLazyRoute
  '/cxdesign/contact': typeof CxdesignContactLazyRoute
  '/cxdesign/graphic-design': typeof CxdesignGraphicDesignLazyRoute
  '/cxdesign/location': typeof CxdesignLocationLazyRoute
  '/cxdesign/web-design': typeof CxdesignWebDesignLazyRoute
  '/cxdesign': typeof CxdesignIndexLazyRoute
}

export interface FileRoutesByTo {
  '/cxdesign/about': typeof CxdesignAboutLazyRoute
  '/cxdesign/app-design': typeof CxdesignAppDesignLazyRoute
  '/cxdesign/contact': typeof CxdesignContactLazyRoute
  '/cxdesign/graphic-design': typeof CxdesignGraphicDesignLazyRoute
  '/cxdesign/location': typeof CxdesignLocationLazyRoute
  '/cxdesign/web-design': typeof CxdesignWebDesignLazyRoute
  '/cxdesign': typeof CxdesignIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/cxdesign/about': typeof CxdesignAboutLazyRoute
  '/cxdesign/app-design': typeof CxdesignAppDesignLazyRoute
  '/cxdesign/contact': typeof CxdesignContactLazyRoute
  '/cxdesign/graphic-design': typeof CxdesignGraphicDesignLazyRoute
  '/cxdesign/location': typeof CxdesignLocationLazyRoute
  '/cxdesign/web-design': typeof CxdesignWebDesignLazyRoute
  '/cxdesign/': typeof CxdesignIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/cxdesign/about'
    | '/cxdesign/app-design'
    | '/cxdesign/contact'
    | '/cxdesign/graphic-design'
    | '/cxdesign/location'
    | '/cxdesign/web-design'
    | '/cxdesign'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cxdesign/about'
    | '/cxdesign/app-design'
    | '/cxdesign/contact'
    | '/cxdesign/graphic-design'
    | '/cxdesign/location'
    | '/cxdesign/web-design'
    | '/cxdesign'
  id:
    | '__root__'
    | '/cxdesign/about'
    | '/cxdesign/app-design'
    | '/cxdesign/contact'
    | '/cxdesign/graphic-design'
    | '/cxdesign/location'
    | '/cxdesign/web-design'
    | '/cxdesign/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  CxdesignAboutLazyRoute: typeof CxdesignAboutLazyRoute
  CxdesignAppDesignLazyRoute: typeof CxdesignAppDesignLazyRoute
  CxdesignContactLazyRoute: typeof CxdesignContactLazyRoute
  CxdesignGraphicDesignLazyRoute: typeof CxdesignGraphicDesignLazyRoute
  CxdesignLocationLazyRoute: typeof CxdesignLocationLazyRoute
  CxdesignWebDesignLazyRoute: typeof CxdesignWebDesignLazyRoute
  CxdesignIndexLazyRoute: typeof CxdesignIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  CxdesignAboutLazyRoute: CxdesignAboutLazyRoute,
  CxdesignAppDesignLazyRoute: CxdesignAppDesignLazyRoute,
  CxdesignContactLazyRoute: CxdesignContactLazyRoute,
  CxdesignGraphicDesignLazyRoute: CxdesignGraphicDesignLazyRoute,
  CxdesignLocationLazyRoute: CxdesignLocationLazyRoute,
  CxdesignWebDesignLazyRoute: CxdesignWebDesignLazyRoute,
  CxdesignIndexLazyRoute: CxdesignIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/cxdesign/about",
        "/cxdesign/app-design",
        "/cxdesign/contact",
        "/cxdesign/graphic-design",
        "/cxdesign/location",
        "/cxdesign/web-design",
        "/cxdesign/"
      ]
    },
    "/cxdesign/about": {
      "filePath": "cxdesign.about.lazy.tsx"
    },
    "/cxdesign/app-design": {
      "filePath": "cxdesign.app-design.lazy.tsx"
    },
    "/cxdesign/contact": {
      "filePath": "cxdesign.contact.lazy.tsx"
    },
    "/cxdesign/graphic-design": {
      "filePath": "cxdesign.graphic-design.lazy.tsx"
    },
    "/cxdesign/location": {
      "filePath": "cxdesign.location.lazy.tsx"
    },
    "/cxdesign/web-design": {
      "filePath": "cxdesign.web-design.lazy.tsx"
    },
    "/cxdesign/": {
      "filePath": "cxdesign.index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
